main/urls.py
from django.urls import path

from . import views

app_name = "main" 
urlpatterns = [
    path("search/", views.search, name="search"),
    path("select_category/", views.select_category, name="select_category"),
    path("", views.index, name="index"),
]

main/models.py
from django.db import models

class Class(models.Model):
    name = models.CharField("class_name", max_length=100)

    def __str__(self):
        return self.name

class Unit(models.Model):
    name = models.CharField("unit_name", max_length=100)
    parent = models.ForeignKey(Class, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Lesson(models.Model):
    name = models.CharField("lesson_name", max_length=100)
    parent = models.ForeignKey(Unit, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class FAQ(models.Model):
    question = models.CharField("Question", max_length=500)
    answer = models.CharField("Answer", max_length=500)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, default="temp_lesson")

    def __str__(self):
        if len(self.question) < 20: return self.question
        return self.question[:20] + "..."

class History(models.Model):
    message = models.CharField("Message", max_length=500)
    is_from_bot = models.BooleanField()
    sent_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.message) < 20: return self.message
        return self.message[:20] + "..."

main/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views import generic
from .models import FAQ, History, Class, Unit, Lesson
    
def index(request):
    classes = Class.objects.all()
    return render(request, "main/chatbot.html", context={"classes": classes})


def search(request):

    hist_list = []
    answer_list = []

    search_word = request.POST.get('search_word')
    hist_list.append(History(message=search_word, is_from_bot=False))
    answer_list .append({"message": search_word, "from": "user"})

    query_set = FAQ.objects.filter(question__icontains=search_word)[:5]

    if len(query_set) <= 0:
        message = f"申し訳ございません。「{search_word}」に関連する情報が見つかりませんでした。"
        hist_list.append(History(message=message, is_from_bot=True))
        answer_list.append({"message": message, "from": "bot", "type": "info"})

    else:
        message = f"「{search_word}」に関する質問："
        hist_list.append(History(message=message, is_from_bot=True))
        answer_list.append({"message": message, "from": "bot", "type": "info"})

        for item in query_set:
            question = f"【質問】{item.question}"
            answer = f"【回答】{item.answer}"
            hist_list.append(History(message=question, is_from_bot=True,))
            hist_list.append(History(message=answer, is_from_bot=True,))
            answer_list.append({"question": question, "answer": answer, "from": "bot", "type": "answer"})

    History.objects.bulk_create(hist_list)
    return JsonResponse({"context": answer_list})


def select_category(request):
    
    level = request.POST.get("level")
    name = request.POST.get("name")
    
    item_list = []
    
    if level == "Class":
        data = Unit.objects.filter(parent__name=name)
        for d in data:
            item_list.append({
                "name": d.name,
                "level": "Unit"
            })
        finished = False
    elif level == "Unit":
        data = Lesson.objects.filter(parent__name=name)
        for d in data:
            item_list.append({
                "name": d.name,
                "level": "Lesson"
            })
        finished = False
    elif level == "Lesson":
        data = FAQ.objects.filter(lesson__name=name)
        for d in data:
            item_list.append({
                "name": d.question,
                "level": "FAQ"
            })
        finished = False
    elif level == "FAQ":
        data = FAQ.objects.get(question=name)
        item_list.append({
            "question": data.question,
            "answer": data.answer
        })
        finished = True

    return JsonResponse({"context": item_list, "finished": finished})

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <style>
      * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
      }
    </style>
    {% block style %}{% endblock %} 

    <title>Chat Bot</title>
  </head>
  <body>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    {% block extrajs %}{% endblock %}
    
  </body>
</html>

main/templates/main/chatbot.html
{% extends 'main/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href={% static "css/chatbot.css" %}>
{% endblock %}

{% block content %}

    <h2 class="title">チャットボット</h2>
    <div id="dialog">
        <div class="wrapper">
        {% for item in classes %}
            <p class="bot message category" data-level="Class">{{ item.name }}</p>
        {% endfor %}
        </div>
    </div>

    <hr>

    <form id="ajax-search" action="{% url 'main:search' %}" method="POST">
        <input type="text" id="search_word" required>
        <button type="submit" >送信</button>
        {% csrf_token %}
    </form>

{% endblock %}

{% block extrajs %}

    <script>
        // フォーム部分
        const w = document.querySelector("#dialog");
        w.scrollTo(0, w.scrollHeight);

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                let cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    let cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        let csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        $('#ajax-search').on('submit', e => {
            e.preventDefault();

            $.ajax({
                'url': '{% url "main:search" %}',
                'type': 'POST',
                'data': {'search_word': $('#search_word').val()},
                'dataType': 'json',
            }).done(response => {
                for (let item of response.context) {
                    let p = null;
                    if (item.from === "user") {
                        let f_div = $('<div>', {class: "flex-wrapper"});
                        p = $('<p>', {text: item.message, class: "user message"});
                        f_div.append(p);
                        $('#dialog').append(f_div);
                    } else if (item.from === "bot") {
                        if (item.type === "info") {
                            p = $('<p>', {text: item.message, class: "bot message"});
                            $('#dialog').append(p);
                        } else if (item.type == "answer") {
                            let div = $('<div>', {class: "wrapper"});
                            p = $('<p>', {text: item.question, class: "bot message"});
                            $(div).append(p);
                            p = $('<p>', {text: item.answer, class: "bot message"});
                            $(div).append(p);
                            $('#dialog').append(div);
                        }
                    }
                }

                w.scrollTo(0, w.scrollHeight);
                $('#search_word').val('');
            });           
        });

    </script>

    <script>
        // カテゴリ選択部分
        function fetch_next(p) {
            $.ajax({
                'url': '{% url "main:select_category" %}',
                'type': 'POST',
                'data': {
                    'level': $(p).data("level"),
                    'name': $(p).text()
                },
                'dataType': 'json',
            }).done(response => {
                if (response.finished) {
                    let div = $('<div>', {class: "wrapper"});
                    let p = $('<p>', {text: "【質問】" + response.context[0].question, class: "bot message"});
                    $(div).append(p);
                    p = $('<p>', {text: "【回答】" + response.context[0].answer, class: "bot message"});
                    $(div).append(p);
                    $('#dialog').append(div);
                } else {
                    let div = $('<div>', {class: "wrapper"});
                    for (let item of response.context) {
                        let p = $('<p>', {text: item.name, class: "bot message category", "data-level": item.level});
                        $(p).on("click", e => {fetch_next(p);});
                        div.append(p);
                    }
                    $('#dialog').append(div);
                }

                w.scrollTo(0, w.scrollHeight);
            });
        }

        for (let p of $(".category"))
            $(p).on("click", e => {fetch_next(p);});

    </script>

{% endblock %}